### ISSUE TITLE
Missing monsters from dungeons

### ISSUE THREAD

**Issue by exiledagain** [finpingvin/pd2-map-dmg-calculator#3]
* Shrieking Terror
* Blunderbore

**Comment by finpingvin** [comment]
Thx I will look into it, do you know which dungeon this is? Never ran any dungeon myself.

**Comment by finpingvin** [comment]
Shrieking terrors are now there, but I can't find blunderbore. Could they appear with another name?

**Comment by finpingvin** [comment]
Found it, I was only reading the first 10 monsters for each map since normal maps dont have more monsters anyway, but dungeons have more monsters (blunderbore was at slot 11).
https://github.com/finpingvin/pd2-gamefiles-parsing/commit/e7ae9a7fb253542da4e4f3b57f0a8cfceb559845
Now blunderbore shows up in the dungeons :)

**Comment by finpingvin** [comment]
The dungeons look correct to you now?
