### ISSUE TITLE
Monster max health

### ISSUE THREAD

**Issue by exiledagain** [finpingvin/pd2-map-dmg-calculator#4]
There's a problem with the max health of monsters. 

`scarab3Crypt` has `MaxHP(H)`: 173 and T1 map is area level 87: `L-HP(H)`: 6412. floor(173\*6412/100) is 11092 max health. Min health is also higher: floor(129\*6412/100) is 8271 min health.

Non-ladder: 6203-8319.

**Comment by finpingvin** [comment]
Thx for the report, I will check your formula when I get some headspace. The HP-values are a bit experimental since I have not found an exact formula of how they are calculated before.
The way they are implemented now is the most accurate we found by soft-verifying it in-game for some of the mobs.

Here is where the HP-values come from if you are curious https://github.com/finpingvin/pd2-gamefiles-parsing/blob/main/main.go#L327 .

**Comment by finpingvin** [comment]
You were spot on, I fixed it here https://github.com/finpingvin/pd2-gamefiles-parsing/commit/c1991a1ac9e291d919d13dce1949222065b81c45

I was using MonLvl3 instead of MonLvl3Ex, and MonLvl3 was incorrectly lvl 88 for scarab3Crypt.
Also missed that hp scaled with difficulty both in monlvl _and_ monstats.

Thx! :) The HP values in the calculator probably still needs some more in-game verification as well..

**Comment by finpingvin** [comment]
Plz let me know if you find any other numbers that look funky
